---
title: "Cronograma"
lang: pt-BR
---

Nesta página, você encontrará o cronograma completo da disciplina, com
links para os materiais de cada aula, incluindo slides, links para 
tutoriais criados para a disciplina, arquivos quarto (.qmd) e outros 
recursos que poderão ser disponibilizados.



# Semana 1

## Aula 1 (18/08/2025) 

- **Tópicos:**

  - Apresentação da disciplina
  - Ambiente Computacional - Parte 1


- **Slides:**

  ::: {.callout-tip}
  ## Para navegar e visualizar 
  
  Clique no símbolo > à direita ou use as teclas: seta para direita →, espaço, 
  ou letra "n"   para avançar. Pressione "F" para modo de tela cheia e "Esc" 
  para sair.
  :::
  
  <iframe src="/slides/slides_aula01.html" width="100%" height="450px"></iframe>
  




# Semana 2

## Aula 2 (25/08/2025) 

- **Tópicos:**

  - Ambiente Computacional - Parte 2
  - Git e GitHub: Visão Geral e Fluxo de Trabalho
  - Introdução Sistema de Publicação Quarto
  - Sessão Prática



- **Slides:**

  ::: {.callout-tip}
  ## Para navegar e visualizar 
  
  Clique no símbolo > à direita ou use as teclas: seta para direita →, espaço, 
  ou letra "n"   para avançar. Pressione "F" para modo de tela cheia e "Esc" 
  para sair.
  :::
  
  <iframe src="/slides/slides_aula02.html" width="100%" height="450px"></iframe>  

- **Arquivo quarto**

  - [01-relatorio (.zip)](arquivos/01-relatorio.zip) 
  
- **Arquivo de dados**

  - [dados (.zip)](arquivos/dados.zip)





